#!/usr/bin/env node
/**
 * Regenerates src/components/icons/index.ts.
 *
 * Lucide ships ~1,800 icons across ~3,700 files. This site uses twelve, so the
 * outlines are inlined instead of pulling in the package. Run this when an icon
 * is added or Lucide is bumped:
 *
 *   node scripts/build-icons.mjs
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = resolve(ROOT, 'src/components/icons/index.ts')

/** Lucide outline icons: exported name -> lucide-static slug. */
const STROKED = {
  Menu: 'menu',
  ArrowRight: 'arrow-right',
  ArrowUpRight: 'arrow-up-right',
  ChevronLeft: 'chevron-left',
  ChevronRight: 'chevron-right',
  Mail: 'mail',
  Phone: 'phone',
  Send: 'send',
  Download: 'download',
  ExternalLink: 'external-link',
  FileText: 'file-text',
  LoaderCircle: 'loader-circle',
  X: 'x'
}

/** Brand marks: Lucide v1 dropped these, so they come from Simple Icons. */
const FILLED = { Github: 'github' }

const inner = (svg) =>
  svg
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>[\s\S]*$/, '')
    .replace(/<title>[\s\S]*?<\/title>/g, '')
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .join('')

async function fetchSvg(url) {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`)
  return inner(await res.text())
}

const q = (s) => `'${s.replace(/'/g, "\\'")}'`

const header = `/**
 * Local icon set — GENERATED by scripts/build-icons.mjs. Do not hand-edit.
 *
 * Official Lucide outlines (ISC) plus the GitHub mark from Simple Icons (CC0),
 * inlined so the site does not depend on the full ~3,700-file icon package.
 *
 * shadcn-vue components generated by the CLI import from 'lucide-vue-next';
 * repoint those imports here (see CLAUDE.md).
 */
import { defineComponent, h, type PropType } from 'vue'

const SIZE_PROP = { size: { type: [Number, String] as PropType<number | string>, default: 24 } }

const OUTLINE = {
  xmlns: 'http://www.w3.org/2000/svg',
  viewBox: '0 0 24 24',
  fill: 'none',
  stroke: 'currentColor',
  'stroke-width': '2',
  'stroke-linecap': 'round',
  'stroke-linejoin': 'round'
} as const

const SOLID = {
  xmlns: 'http://www.w3.org/2000/svg',
  viewBox: '0 0 24 24',
  fill: 'currentColor'
} as const

function icon(name: string, base: Record<string, string>, body: string) {
  return defineComponent({
    name,
    props: SIZE_PROP,
    setup(props, { attrs }) {
      return () =>
        h('svg', { ...base, width: props.size, height: props.size, ...attrs, innerHTML: body })
    }
  })
}
`

const lines = []
for (const [name, slug] of Object.entries(STROKED)) {
  const body = await fetchSvg(`https://unpkg.com/lucide-static@latest/icons/${slug}.svg`)
  lines.push(`export const ${name} = icon(${q(name)}, OUTLINE, ${q(body)})`)
}
for (const [name, slug] of Object.entries(FILLED)) {
  const body = await fetchSvg(`https://unpkg.com/simple-icons@latest/icons/${slug}.svg`)
  lines.push(`export const ${name} = icon(${q(name)}, SOLID, ${q(body)})`)
}
lines.push('')
lines.push('/** Lucide renamed Loader2 to LoaderCircle in v1; keep the familiar alias. */')
lines.push('export const Loader2 = LoaderCircle')

await mkdir(dirname(OUT), { recursive: true })
await writeFile(OUT, `${header}\n${lines.join('\n')}\n`)
console.log(`Wrote ${OUT} (${Object.keys(STROKED).length + Object.keys(FILLED).length} icons)`)
