/**
 * Local icon set — GENERATED by scripts/build-icons.mjs. Do not hand-edit.
 *
 * Official Lucide outlines (ISC) plus the GitHub mark from Simple Icons (CC0),
 * inlined so the site does not depend on the full ~3,700-file icon package.
 *
 * shadcn-vue components generated by the CLI import from 'lucide-vue-next';
 * repoint those imports here (see CLAUDE.md).
 */
import { defineComponent, h, type PropType } from 'vue'

const SIZE_PROP = { size: { type: [Number, String] as PropType<number | string>, default: 24 } }

const OUTLINE = {
  xmlns: 'http://www.w3.org/2000/svg',
  viewBox: '0 0 24 24',
  fill: 'none',
  stroke: 'currentColor',
  'stroke-width': '2',
  'stroke-linecap': 'round',
  'stroke-linejoin': 'round'
} as const

const SOLID = {
  xmlns: 'http://www.w3.org/2000/svg',
  viewBox: '0 0 24 24',
  fill: 'currentColor'
} as const

function icon(name: string, base: Record<string, string>, body: string) {
  return defineComponent({
    name,
    props: SIZE_PROP,
    setup(props, { attrs }) {
      return () =>
        h('svg', { ...base, width: props.size, height: props.size, ...attrs, innerHTML: body })
    }
  })
}

export const Menu = icon('Menu', OUTLINE, '<path d="M4 5h16" /><path d="M4 12h16" /><path d="M4 19h16" />')
export const ArrowRight = icon('ArrowRight', OUTLINE, '<path d="M5 12h14" /><path d="m12 5 7 7-7 7" />')
export const ArrowUpRight = icon('ArrowUpRight', OUTLINE, '<path d="M7 7h10v10" /><path d="M7 17 17 7" />')
export const ChevronLeft = icon('ChevronLeft', OUTLINE, '<path d="m15 18-6-6 6-6" />')
export const ChevronRight = icon('ChevronRight', OUTLINE, '<path d="m9 18 6-6-6-6" />')
export const Mail = icon('Mail', OUTLINE, '<path d="m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7" /><rect x="2" y="4" width="20" height="16" rx="2" />')
export const Phone = icon('Phone', OUTLINE, '<path d="M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384" />')
export const Send = icon('Send', OUTLINE, '<path d="M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z" /><path d="m21.854 2.147-10.94 10.939" />')
export const Download = icon('Download', OUTLINE, '<path d="M12 15V3" /><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><path d="m7 10 5 5 5-5" />')
export const ExternalLink = icon('ExternalLink', OUTLINE, '<path d="M15 3h6v6" /><path d="M10 14 21 3" /><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />')
export const FileText = icon('FileText', OUTLINE, '<path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z" /><path d="M14 2v5a1 1 0 0 0 1 1h5" /><path d="M10 9H8" /><path d="M16 13H8" /><path d="M16 17H8" />')
export const LoaderCircle = icon('LoaderCircle', OUTLINE, '<path d="M21 12a9 9 0 1 1-6.219-8.56" />')
export const X = icon('X', OUTLINE, '<path d="M18 6 6 18" /><path d="m6 6 12 12" />')
export const Github = icon('Github', SOLID, '<path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/>')

/** Lucide renamed Loader2 to LoaderCircle in v1; keep the familiar alias. */
export const Loader2 = LoaderCircle
